# NVIDIA Pytorch Base Container
FROM nvcr.io/nvidia/pytorch:22.02-py3

# Update apt and pip
RUN apt update
RUN python3 -m pip install --no-cache-dir --upgrade pip

# Install seqio and wandb
RUN pip install seqio wandb IProgress huggingface_hub ipywidgets t5

# Install transformers
RUN git clone https://github.com/huggingface/transformers.git && \
    cd transformers && \
    pip install -e . && \
    cd ..

# Install datasets and transformers
RUN pip install datasets==1.18.3 jupyterlab

# add to path
ENV PYTHONPATH="${PYTHONPATH}:/workspace/transformers"
