# NVIDIA Pytorch Base Container
FROM nvcr.io/nvidia/pytorch:22.02-py3

# Update apt and pip
RUN apt update
RUN python3 -m pip install --no-cache-dir --upgrade pip

# Install seqio and wandb
RUN pip install seqio wandb IProgress huggingface_hub ipywidgets t5

# Clone He and Lester repos
RUN git clone https://github.com/jxhe/unify-parameter-efficient-tuning.git && \
    git clone https://github.com/google-research/prompt-tuning.git

# Install He repo requirements
RUN cd unify-parameter-efficient-tuning && \
    pip install -e . && \
    pip install datasets==1.18.3 && \
    cd ..

# Add repos to PYTHONPATH
ENV PYTHONPATH="${PYTHONPATH}:/workspace/unify-parameter-efficient-tuning"
ENV PYTHONPATH="${PYTHONPATH}:/workspace/prompt-tuning"

